name = "StaircaseShenanigans"
uuid = "c2bb06a8-94f3-4279-b990-30bf3ab8ba6f"
authors = ["Josef Bisits <jbisits@gmail.com>"]
version = "0.0.1"

[deps]
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
SeawaterPolynomials = "d496a93d-167e-4197-9f49-d3af4ff8fe40"

[compat]
Oceananigans = "0.91"
Reexport = "1.2"
SeawaterPolynomials = "0.3"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
