function animate_tracers end
function animate_tracers_anomaly end
function animate_density end
function animate_vertical_velocity end
function animate_density_anomaly end
function animate_profile_in_S_Θ_space end
function visualise_initial_conditions end
function visualise_initial_density end
